version: '3.4'

services:
  querydb:
        container_name: sqlserver-querydb-container
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=Password123
        restart: always
        ports:
          - "1436:1433"
 
  commanddb:
        container_name: mongo-commandb-container
        restart: always
        volumes:
        - mongo-data:/data/db
        ports:
          - "27017:27017"
        environment:
          - MONGO_INITDB_ROOT_USERNAME=admin  
          - MONGO_INITDB_ROOT_PASSWORD=admin
          - MONGO_INITDB_DATABASE=socialMedia
        command: --auth

  zookeeper:
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CREATE_TOPICS=socialMedia:1:1
    depends_on:
      - zookeeper
    
  post.cmd.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - MongoDbConfig__ConnectionString=mongodb://localhost:27017
      - MongoDbConfig__Database=socialMedia
      - MongoDbConfig__Collection=eventStore
      - MongoDbConfig__UserName=admin
      - MongoDbConfig__Password=admin
      - MongoDbConfig__Host=host.docker.internal
      - ProducerConfig__BootstrapServers=host.docker.internal:9092
      - ProducerConfig__Topic=socialMedia
      - KAFKA_TOPIC=socialMedia
    ports:
      - "7080:8080"
      - "7081:8081"
    depends_on:
      - commanddb
      - kafka
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  post.query.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__SqlServer=Data Source=querydb;Initial Catalog=SocialMedia;User ID=sa;Password=Password123;Trust Server Certificate=True
      - ConsumerConfig__BootstrapServers=host.docker.internal:9092
      - ConsumerConfig__GroupId=SM_Consumer
      - ConsumerConfig__AutoOffsetReset=earliest
      - ProducerConfig__EnableAutoCommits=false
      - ProducerConfig__AllowAutoCreateTopics=true
      - KAFKA_TOPIC=socialMedia
    depends_on:
      - querydb
      - kafka
    ports:
      - "9080:8080"
      - "9081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
     
